import React from "react";
import Head from "next/head";

const Layout = (props) => {   
  return (
    <div>
      <Head>
        <title>{props.title||'Bonafide'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/images/logo.svg" />
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossOrigin="anonymous"/>
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap" rel="stylesheet"/>
      </Head>
      <body>
        {props.children}
      </body>
    </div>
  );
};
export default Layout;